server-src/DailyReport.Presentation.Web/Areas/PatientModule/Models/ContactInformationViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using DailyReport.Domain.Models;

namespace DailyReport.Presentation.Web.Areas.PatientModule.Models
{
    public class ContactInformationViewModel : PatientBaseViewModel
    {
        public IEnumerable<SelectListItem> ContactInformationTypeList { get; set; }

        [Required]
        public int ContactInformationTypeId { get; set; }

        [Required]
        public string Data { get; set; }
    }
}

server-src/DailyReport.Presentation.Web/Areas/ProfileModule/Models/ContactInformationViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using DailyReport.Domain.Models;

namespace DailyReport.Presentation.Web.Areas.ProfileModule.Models
{
    public class ContactInformationViewModel
    {
        public IEnumerable<SelectListItem> ContactInformationTypeList { get; set; }

        [Required]
        public int ContactInformationTypeId { get; set; }

        [Required]
        public string Data { get; set; }
    }
}

server-src/DailyReport.Presentation.Web/Models/ContactInformationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DailyReport.Presentation.Web.Models
{
    public abstract class ContactInformationViewModel
    {
        public class Add
        {
            [Required]
            public string Type { get; set; }

            [Required]
            public string Value { get; set; }
        }
    }
}

server-src/DailyReport.Presentation.Web/Areas/PatientModule/Controllers/ContactInformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using DailyReport.Domain.Infrastructure.Services;
using DailyReport.Presentation.Web.Areas.PatientModule.Models;
using DailyReport.Presentation.Web.Extensions;

namespace DailyReport.Presentation.Web.Areas.PatientModule.Controllers
{
    public class ContactInformationController : Controller
    {
        private readonly IPatientService _patientService;
        private readonly IOrganizationService _organizationService;
        private readonly IContactInformationService _contactInformationService;

        public ContactInformationController(IPatientService patientService, IOrganizationService organizationService, IContactInformationService contactInformationService)
        {
            _patientService = patientService;
            _organizationService = organizationService;
            _contactInformationService = contactInformationService;
        }

        public ActionResult Index(int patientId)
        {
            var organization = _organizationService.GetById(ClaimsPrincipal.Current.GetOrganizationId());
            var patient = _patientService.GetById(patientId);
            var contactInformationTypes = _contactInformationService.GetTypes();

            return View(new ContactInformationViewModel
            {
                Organization = organization,
                Patient = patient,
                ContactInformationTypeList = contactInformationTypes.GetSelectList()
            });
        }

        public ActionResult Edit(int patientId, int id)
        {
            var organization = _organizationService.GetById(ClaimsPrincipal.Current.GetOrganizationId());
            var patient = _patientService.GetById(patientId);
            var contactInformationTypes = _contactInformationService.GetTypes();

            // Fetch the contact information
            var contactInformation = _contactInformationService.GetById(id);

            return View(new ContactInformationEditViewModel
            {
                Organization = organization,
                Patient = patient,
                ContactInformationTypeList = contactInformationTypes.GetSelectList(),

                ContactInformationId = contactInformation.Id,
                ContactInformationTypeId = contactInformation.TypeId,
                Data = contactInformation.Data
            });
        }

        [HttpPost]
        public ActionResult Edit(int patientId, int id, ContactInformationEditViewModel viewModel)
        {
            var organization = _organizationService.GetById(ClaimsPrincipal.Current.GetOrganizationId());
            var patient = _patientService.GetById(patientId);

            if (ModelState.IsValid)
            {
                _contactInformationService.Update(id, viewModel.ContactInformationTypeId, viewModel.Data);

                return RedirectToAction("Edit", new { patientId = patient.Id, id = id });
            }


            var contactInformationTypes = _contactInformationService.GetTypes();

            // Remap viewmodel
            viewModel.Organization = organization;
            viewModel.Patient = patient;
            viewModel.ContactInformationId = id;
            viewModel.ContactInformationTypeList = contactInformationTypes.GetSelectList();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int patientId, int id)
        {
            _contactInformationService.Deactivate(id);

            return RedirectToAction("Index", new { patientId });
        }

        [ChildActionOnly]
        public ActionResult ContactInformations(int patientId, bool disableEditing = false, bool enableText = false)
        {
            return PartialView(new ContactInformationPartialViewModel
            {
                PatientId = patientId,
                ContactInformations = _patientService.ContactInformations.FindAll(patientId),
                DisableEditing = disableEditing,
                EnableText = enableText
            });
        }
    }
}

server-src/DailyReport.Presentation.Web/Areas/ProfileModule/Controllers/ContactInformationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using DailyReport.Domain.Infrastructure.Services;
using DailyReport.Presentation.Web.Areas.ProfileModule.Models;
using DailyReport.Presentation.Web.Extensions;
using Microsoft.AspNet.Identity;

namespace DailyReport.Presentation.Web.Areas.ProfileModule.Controllers
{
    public class ContactInformationController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IContactInformationService _contactInformationService;

        public ContactInformationController(IEmployeeService employeeService, IContactInformationService contactInformationService)
        {
            _employeeService = employeeService;
            _contactInformationService = contactInformationService;
        }

        public ActionResult Index()
        {
            var contactInformationTypes = _contactInformationService.GetTypes();

            return View(new ContactInformationViewModel
            {
                ContactInformationTypeList = contactInformationTypes.GetSelectList()
            });
        }
        
        public ActionResult Edit(int id)
        {
            var contactInformationTypes = _contactInformationService.GetTypes();

            // Fetch the contact information
            var contactInformation = _contactInformationService.GetById(id);

            return View(new ContactInformationEditViewModel
            {
                ContactInformationTypeList = contactInformationTypes.GetSelectList(),

                ContactInformationId = contactInformation.Id,
                ContactInformationTypeId = contactInformation.TypeId,
                Data = contactInformation.Data
            });
        }

        [HttpPost]
        public ActionResult Edit(int id, ContactInformationEditViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                _contactInformationService.Update(id, viewModel.ContactInformationTypeId, viewModel.Data);

                return RedirectToAction("Edit", new { id });
            }


            var contactInformationTypes = _contactInformationService.GetTypes();

            // Remap viewmodel
            viewModel.ContactInformationId = id;
            viewModel.ContactInformationTypeList = contactInformationTypes.GetSelectList();

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            _contactInformationService.Deactivate(id);

            return RedirectToAction("Index");
        }

        [ChildActionOnly]
        public ActionResult ContactInformations(bool disableEditing = false, bool enableText = false)
        {
            return PartialView(new ContactInformationPartialViewModel
            {
                ContactInformations = _employeeService.ContactInformations.FindAll(User.Identity.GetUserId<int>()),
                DisableEditing = disableEditing,
                EnableText = enableText
            });
        }
    }
}

server-src/DailyReport.Presentation.Web/Areas/ProfileModule/Views/ContactInformation/ContactInformationForm.cshtml
@model DailyReport.Presentation.Web.Areas.ProfileModule.Models.ContactInformationViewModel

<div class="form-group">
    <label class="control-label col-md-2">Type</label>
    <div class="col-md-10">
        @Html.DropDownListFor(model => model.ContactInformationTypeId, Model.ContactInformationTypeList, new { @class = "default-select2" })
        @Html.ValidationMessageFor(model => model.ContactInformationTypeId, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    <label class="control-label col-md-2">Værdi</label>
    <div class="col-md-10">
        @Html.EditorFor(model => model.Data, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Data, "", new { @class = "text-danger" })
    </div>
</div>

server-src/DailyReport.Presentation.Web/Areas/ProfileModule/Views/ContactInformation/ContactInformations.cshtml
@model DailyReport.Presentation.Web.Areas.ProfileModule.Models.ContactInformationPartialViewModel

@if (Model.ContactInformations.Any())
{
    <dl>
        @foreach (var contactInformation in Model.ContactInformations)
        {
            <dt>
                @contactInformation.Type
                @if (!Model.DisableEditing) { 
                    <div class="pull-right">
                        <a href="@Url.GetMyContactInformationEditUrl(contactInformation.Id)"><span aria-hidden="true" class="glyphicon glyphicon-edit"></span></a>
                        <a href="@Url.GetMyContactInformationEditUrl(contactInformation.Id)"><span aria-hidden="true" class="glyphicon glyphicon-remove"></span></a>
                    </div>
                }
            </dt>
            <dd>@contactInformation.Data</dd>
        }
    </dl>
}
else if (Model.EnableText)
{
    <p class="text-muted text-center">
        Patienten har ikke tilknytten nogen kontaktinformationer
    </p>
}

server-src/DailyReport.Presentation.Web/Areas/ProfileModule/Views/ContactInformation/Edit.cshtml
@model DailyReport.Presentation.Web.Areas.ProfileModule.Models.ContactInformationEditViewModel

<h1 class="page-header">Kontaktinformationer</h1>

<div class="row">
    <div class="col-md-8">
        <p>Lav ændringer til informationen. Du burde kun gøre dette hvis der har været en tastefejl - hvis patienten har fået nyt nummer f.eks. så skal du slette denne information og oprette en ny.</p>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @{
            Html.RenderPartial("ContactInformationForm", Model);
                }

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Gem ændringer" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }

        <h3>Slet information</h3>
        <p>
            Er denne information ikke brug længere? Dette kan være hvis patienten har skiftet telefonnummer eller email..
        </p>
        
        @using (Html.BeginForm("Delete", "ContactInformation", new { Id = Model.ContactInformationId }, FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            
            <button class="btn btn-danger" type="submit">Slet</button>
        }
    </div>
    <div class="col-md-4">
        @{
            Html.RenderAction("ContactInformations", "ContactInformation");
        }
    </div>
</div>

server-src/DailyReport.Presentation.Web/Areas/ProfileModule/Views/ContactInformation/Index.cshtml
@model DailyReport.Presentation.Web.Areas.ProfileModule.Models.ContactInformationViewModel

<h1 class="page-header">Kontaktinformationer</h1>

<div class="row">
    <div class="col-md-8">
        <p>
            Tilføj en kontaktinformation så det er muligt for dine kollegaer at komme i kontakt med dig.
        </p>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                @{
                    Html.RenderPartial("ContactInformationForm", Model);
                }

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Tilføj" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-md-4">
        @{
            Html.RenderAction("ContactInformations", "ContactInformation");
        }
    </div>
</div>