server-src/DailyReport.Presentation.Web/Models/ContactPersonViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DailyReport.Presentation.Web.Models
{
    public class ContactPersonViewModels
    {
        public class Add
        {
            [Required]
            public int EmployeeId { get; set; }

            [Required]
            public bool CompletePrevious { get; set; }
        }

        public class Complete
        {
            [Required]
            public int Id { get; set; }
        }
    }
}

server-src/DailyReport.Presentation.Web/Areas/PatientModule/Controllers/ContactPersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using DailyReport.Domain.Infrastructure.Services;
using DailyReport.Presentation.Web.Areas.PatientModule.Models;
using DailyReport.Presentation.Web.Extensions;

namespace DailyReport.Presentation.Web.Areas.PatientModule.Controllers
{
    public class ContactPersonController : Controller
    {
        private readonly IPatientService _patientService;
        private readonly IOrganizationService _organizationService;
        private readonly IEmployeeService _employeeService;

        public ContactPersonController(IPatientService patientService, IOrganizationService organizationService, IContactInformationService contactInformationService, IEmployeeService employeeService)
        {
            _patientService = patientService;
            _organizationService = organizationService;
            _employeeService = employeeService;
        }

        //public ActionResult Index(int patientId)
        //{
        //    var organization = _organizationService.GetById(ClaimsPrincipal.Current.GetOrganizationId());
        //    var patient = _patientService.GetById(patientId);
        //    var contactPersons = _patientService.ContactPersons.FindAll(patient.Id);
        //    var employees = _employeeService.FindAll(organization.Id)
        //        .Where(x => contactPersons.All(y => x.Id != y.Employee.Id || (x.Id == y.Employee.Id && y.IsEnded)));

        //    return View(new PatientContactPersonsViewModel
        //    {
        //        Organization = organization,
        //        Patient = patient,
        //        ContactPersons = contactPersons,
        //        EmployeesList = employees.GetSelectList()
        //    });
        //}

        //[HttpPost]
        //public ActionResult Index(int patientId, PatientContactPersonsViewModel viewModel)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _patientService.ContactPersons.Add(patientId, viewModel.EmployeeId, viewModel.CompletePreviousContactPersons);

        //        return RedirectToAction("Index", new { Id = patientId });
        //    }

        //    var organization = _organizationService.GetById(ClaimsPrincipal.Current.GetOrganizationId());
        //    var patient = _patientService.GetById(patientId);
        //    var contactPersons = _patientService.ContactPersons.FindAll(patient.Id);
        //    var employees = _employeeService.FindAll(organization.Id)
        //        .Where(x => contactPersons.All(y => x.Id != y.Employee.Id || (x.Id == y.Employee.Id && y.IsEnded)));

        //    viewModel.EmployeesList = employees.GetSelectList();
        //    viewModel.ContactPersons = contactPersons;
        //    viewModel.Organization = organization;
        //    viewModel.Patient = patient;
        //    return View(viewModel);
        //}

        [HttpPost]
        public ActionResult Complete(int patientId, int relationshipId)
        {
            _patientService.ContactPersons.Complete(relationshipId);

            return RedirectToAction("Index", new { patientId });
        }
    }
}

server-src/DailyReport.Presentation.Web/Areas/PatientModule/Views/ContactPerson/Index.cshtml
@model DailyReport.Presentation.Web.Areas.PatientModule.Models.PatientContactPersonsViewModel

@{
    ViewBag.Title = "Edit";
    ViewBag.PageTitle = Model.Patient.GetDisplayName();
    Layout = "~/Areas/PatientModule/Views/Shared/_PatientLayout.cshtml";
}
<div class="row">
    <div class="col-md-7">
        @if (Model.ContactPersons.Any())
        {
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Navn</th>
                        <th>Periode</th>
                        <th></th>
                    </tr>
                </thead>

                @foreach (var contactPerson in Model.ContactPersons)
                {
                    <tr>
                        <td>@contactPerson.Employee.GetDisplayName()</td>
                        <td>@contactPerson.TimeStarted.ToShortDateString()</td>
                        <td>
                            @if (contactPerson.IsEnded)
                            {
                                @contactPerson.TimeEnded.Value.ToShortDateString()
                            }
                            else
                            {
                                using (Html.BeginForm("Complete", "ContactPerson", new { PatientId = contactPerson.PatientId, RelationshipId = contactPerson.Id }))
                                {
                                    <button type="submit" class="btn btn-danger">Afslut periode</button>
                                }
                            }
                        </td>
                    </tr>
                }

            </table>
        }
        else
        {
            <p class="text-center text-muted">
                @Model.Patient.GetDisplayName() har ikke haft nogen kontaktpersoner
            </p>
        }
    </div>
    <div class="col-md-5">
        @if (Model.EmployeesList.Any())
        {
            using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h3>Tilføj ny kontaktperson</h3>
                    <div class="form-group">
                        <label class="control-label col-md-2">Vælg ansat</label>
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.EmployeeId, Model.EmployeesList, new { @class = "default-select2" })
                            @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="checkbox col-md-12 col-md-offset-2">
                            <label>
                                @Html.CheckBoxFor(model => model.CompletePreviousContactPersons) Afslut igangværende kontaktpersoner
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Tilføj" class="btn btn-success" />
                    </div>
                </div>
            }
        }
        else
        {
            <p class="text-muted text-center">Der er ingen ansatte som kan blive tilknyttet som kontaktperson til @Model.Patient.GetDisplayName()</p>
        }
    </div>
</div>